### ISSUE TITLE
'recipe: custom' throws warning, lando fails to start

### ISSUE THREAD

**Issue by coolemur** [HBFCrew/lando-docs-examples#1]
You might want to update this code removing "recipe: custom" line

```
name: grav-test
recipe: custom
services:
  appserver:
    type: php:7.0
    # Serve php by either apache or nginx. You can put in any `service:version`
    # string that is supported by Lando's nginx and apache services.
    via: apache
    version: 2.4
    webroot: web
    # Optionally serve php over https
    ssl: false
```
